evn: yukx
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yukx
    url: jdbc:mysql://127.0.0.1/docker?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    jpa:
      show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
